### ISSUE TITLE
How to restart motor after flipping over

### ISSUE THREAD

**Issue by zzzzzyh111** [RAFALAMAO/hector-quadrotor-noetic#9]
Hi, I am doing a reinforcement-leaning-based obstacle avoidance simulation with your quadrotor model. But I encountered a problem once the UAV flippered over due to impact, the motor just shut down. I tried to reset the position of the UAV and set a Z linear velocity to the UAV. But the UAV still kept still. This problem can only be solved by relaunching the file and rerunning the program. Can I ask if is there any programming-based method to solve this issue? 

Thanks in advance!

**Comment by zzzzzyh111** [comment]
Related information is shown in the below image
![WechatIMG6687](https://user-images.githubusercontent.com/90167493/196886957-5902fc91-8e85-45b6-b60a-89688e87252a.jpeg)

**Comment by RAFALAMAO** [comment]
This is a default action when drone flips over you need to relaunch, so if you want to modify it, you need to search it in code and rebuild de ros package.

I would recommend you to use Airsim, because it's more advanced.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zzzzzyh111** [comment]
Sorry for my late response, mate. I have figured out how to restart the motor after flipping over. Since the motor status is set to be **False** after flipping over, what we need to do is to modify it to be **True,** and everything works smoothly. Thanks for your advice anyway, and I wish you all the best!
